### ISSUE TITLE
Kappa advection scheme only working for scalars

### ISSUE THREAD

**Issue by samoliverowens** [uDALES/u-dales#103]
Setting `iadv_thl = 7` (and not using scalars) firstly means that `ih` is set to 2, which means the x grid arrays (`dxf` etc) are not populated correctly, resulting in a division by zero when calculating e.g `dxfi`. 

We also have the problem that `advecc_kappa` uses `ihc` and arrays like `dxfci` etc rather than `dxfi`, which aren't populated unless `iadv_sv == 7`.

I guess we should also populate these arrays when any variable is running the kappa scheme, rather than just scalars. If so, we'd need to think about what we set `ih` to, given that it is used in this section - it'd be nice to be able to set it to 1 as this would solve the first problem.

**Comment by samoliverowens** [comment]
I will try fix this at some point, but for now we should just say that the kappa scheme is only available for scalars.

**Comment by dmey** [comment]
Shall we move this to the Future milestone? Are you OK to add this to the docs for now? I can also do it...

**Comment by samoliverowens** [comment]
> Shall we move this to the Future milestone? Are you OK to add this to the docs for now? I can also do it...

Yes that's a good idea, and I'll have a look at the docs.
