### ISSUE TITLE
T5.4 Remove the cookie-cutter from the main uDALES documentation.

### ISSUE THREAD

**Issue by mvreeuwijk** [uDALES/u-dales#222]

**Comment by dc2917** [comment]
@mvreeuwijk 

Just to clarify, is this to remove the installation via cookie-cutter section from the build instructions, or to actually delete the [uDALES/cookiecutter-u-dales](https://github.com/uDALES/cookiecutter-u-dales) repository?

**Comment by mvreeuwijk** [comment]
@dc2917 

Just the instructions -- that way we can reinstate the cookie-cutter easily in the future should we need it.
