### ISSUE TITLE
dT in wall function for momentum when iwalltemp/=2

### ISSUE THREAD

**Issue by tomgrylls** [uDALES/u-dales#23]
The wall function for momentum uses the temperature difference between the wall and the adjacent cell, `dT`. However, under neutral conditions or under non-neutral conditions when `iwalltemp/=2` (zero flux or constant flux BCs used) this term is still calculated even though the wall temperature is not being modelled. This means that the wall function will have a stability term based off a temperature difference that is not being modelled. 

This will occur:
1. in neutral conditions if there is a difference between the arbitrarily defined air temperature (typically `thl=288`) and the values assigned in `Tfacinit.f90`. This can be avoided by ensuring that these are equal and therefore `dT=0` by definition (currently done in preprocessing but maybe this should be automated as it should not need to be considered when modelling neutral conditions). Perhaps have a switch for `if (ltempeq)` where `Tfacinit.f90` is read.
2. When `iwalltemp=1` the air temperature is non-uniform and `dT` will be non-zero. Potential solution would be to define a switch within each case in `wfuno.f90` where `dT=0` if `iwalltemp=1`. Or may be easier to just edit function `unom` and we just need `Ribl0=0` under these conditions. @ivosuter - thoughts?

The consequence of this bug is that under these specific conditions we can expect changes to the applied wall shear stress due this stability term.

**Comment by dmey** [comment]
Do we need further checks for this or can we close it?

**Comment by ivosuter** [comment]
I said I would have a last look at it, but that we believe it's done.
So gonna check wfmneutral now

**Comment by dmey** [comment]
Cool thanks!

**Comment by ivosuter** [comment]
Hmm it appears to me there are indeed some mistakes in both, wfm_neutral and wf_uno in the edge cases. On the staggered grid the tangential velocities on a surface are at the vertices of the gridcell/surface. The edge cases (the edge of the building) therefore only experieces half a gridcell of solid -> we simply assume the flux is also halfed. Can someone double check that the indeces make sense and were not forgotten:   (i'll post a list in a few minutes)

**Comment by ivosuter** [comment]
ui-1   ui   ui+1      ui+2
  o-----o-----o-----o
  |...................................|
  |...................................|
  |...................................|
  ui-1 and ui+2 only experience half a cell

**Comment by ivosuter** [comment]
wfm_neutral:
do we need w bottom cases at all? since blocks are never floating the bottom is always the floor? If we do, shouldn't it be  (on lines 142,251,352 and 461) 
k = block(n, 5)

On line 518/519 a  'i = block(n, 2) + 1' is missing

wfm_uno:
same story
should it be 'k = block(n, 5)' on lines 357,497,626,763

On line 835/836 a  'i = block(n, 2) + 1' is missing

**Comment by dmey** [comment]
@samoliverowens should we ask @tomgrylls to look into this? @ivosuter made some comments some time ago about this issue but I am not the right person to look into this.

**Comment by samoliverowens** [comment]
> @samoliverowens should we ask @tomgrylls to look into this? @ivosuter made some comments some time ago about this issue but I am not the right person to look into this.

I'll have a look too, but yes @tomgrylls will be better with this.

**Comment by tomgrylls** [comment]
> wfm_neutral:
> do we need w bottom cases at all? since blocks are never floating the bottom is always the floor? If we do, shouldn't it be (on lines 142,251,352 and 461)
> k = block(n, 5)

Agreed I think the best option is to edit these to `k = block(n, 5)`. This loop will be used in situations where blocks start from non-zero values. We do not have them floating but in complex morphologies where blocks are positioned above other blocks this will occur.

> 
> On line 518/519 a 'i = block(n, 2) + 1' is missing
> 

Good spot - yes agreed we should add this line.

> wfm_uno:
> same story
> should it be 'k = block(n, 5)' on lines 357,497,626,763
> 
> On line 835/836 a 'i = block(n, 2) + 1' is missing

Both of these are equivalent to the points above. And therefore again I am in agreement of changing them. As shown from the discussion above `wfmneutral` is directly based upon `wf_uno` and therefore it makes sense that these are consistent across both.

I will create a pull request in the next couple of days and set @ivosuter as reviewer in order to have a final check on the above.
