### ISSUE TITLE
facetareas.inp only written when performing SEB simulations

### ISSUE THREAD

**Issue by mvreeuwijk** [uDALES/u-dales#243]
Whenever there is a geometry, the udales preprocessing files should produce a facetareas.inp file, since udbase relies on it. Currently this file is only written when performing surface energy balance simulations.

**Comment by madDipanjan** [comment]
Updated it. Now facetarea.inp.xxx gets written always. Commit 2e36e0f587a804e1b30479d45fda61bf0a7bdb90

**Comment by madDipanjan** [comment]
Issue resolved. Note the correct file name is "facetarea.inp.xxx", and not "facetareas.inp.xxx"
