### ISSUE TITLE
Add statistics variables to restart files

### ISSUE THREAD

**Issue by bss116** [uDALES/u-dales#41]
Currently only field variables are saved in the restart initd and inits files. If the time-averaged statistics variables are added, then the time-average of the statistics output will no longer be limited by the runtime. The variables that need to be added are a subset of the ones loaded from `modfields` by the subroutine `statsdump` in `modstatsdump.f90`: https://github.com/uDALES/u-dales/blob/9d25e6f25db5b4571e6f069ed330086ce51ca6a1/src/modstatsdump.f90#L333. This is done in `modsave.f90` to write additional variables to the restart files and in `modstartup.f90` to read in the additional variables at warmstart.

**Comment by mvreeuwijk** [comment]
This would make the files extremely large which is undesirable. A warning about statistics not aligned with the output frequency of restart files may be a pragmatic solution.
